# Generated by Django 5.0.7 on 2024-08-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100)),
                ('instruction_type', models.CharField(max_length=500)),
                ('instructor_hours', models.DateTimeField(verbose_name='Date & Time')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer_name', models.CharField(max_length=100)),
                ('performerance_type', models.CharField(max_length=150)),
                ('performer_description', models.CharField(max_length=500)),
                ('instructor', models.ManyToManyField(to='main_app.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
